<a href="https://colab.research.google.com/github/bits-blitzz/my_first_repo/blob/main/numpy_prac_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#### Q1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [ ]:
arr_q1=np.random.randint(1,101,(3,3))

In [ ]:
arr_q1

array([[69, 27,  4],
       [37, 97, 44],
       [74, 62, 29]])

In [ ]:
#interchanging rows and columns
arr_q1.T

array([[69, 37, 74],
       [27, 97, 62],
       [ 4, 44, 29]])

#### Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [ ]:
arr_q2=np.random.randint(1,10,10)

In [ ]:
arr_q2

array([3, 4, 3, 8, 6, 8, 2, 6, 1, 7])

In [ ]:
#reshaping into 2X5 array
np.reshape(arr_q2, (2,5))

array([[3, 4, 3, 8, 6],
       [8, 2, 6, 1, 7]])

In [ ]:
#reshaping into 5X2 array
np.reshape(arr_q2,(5,2))

array([[3, 4],
       [3, 8],
       [6, 8],
       [2, 6],
       [1, 7]])

#### Q3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
ar_q3=np.random.rand(4,4)

In [ ]:
ar_q3=np.round(ar_q3,2)

In [ ]:
ar_q3

array([[0.9 , 0.24, 0.86, 0.19],
       [0.02, 0.37, 0.15, 0.48],
       [0.1 , 0.84, 0.43, 0.88],
       [0.79, 0.06, 0.36, 0.41]])

In [ ]:
ar_zeros=np.zeros((6,6))

In [ ]:
ar_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
ar_zeros[1:5,1:5]=ar_q3

In [ ]:
ar_zeros

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.9 , 0.24, 0.86, 0.19, 0.  ],
       [0.  , 0.02, 0.37, 0.15, 0.48, 0.  ],
       [0.  , 0.1 , 0.84, 0.43, 0.88, 0.  ],
       [0.  , 0.79, 0.06, 0.36, 0.41, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

#### Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
ar_q4=np.arange(10,61,5)

In [ ]:
ar_q4

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

#### Q5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
str=['python','numpy','pandas']
arr_q5=np.array(str)

In [ ]:
arr_q5

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.upper(arr_q5)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.lower(arr_q5)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.capitalize(arr_q5)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
np.char.title(arr_q5)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

#### Q6.  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
words=["Hello","Sir","How\'s","My","Assignment"]

ar_q6=np.array(words)

In [ ]:
ar_q6

array(['Hello', 'Sir', "How's", 'My', 'Assignment'], dtype='<U10')

In [ ]:
q=np.char.join(" ",ar_q6)

In [ ]:
print(q)

['H e l l o' 'S i r' "H o w ' s" 'M y' 'A s s i g n m e n t']


#### Q7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1= np.random.randint(1,4,(3,4))

In [ ]:
arr2= np.random.randint(1,4,(3,4))

In [ ]:
arr1

array([[2, 2, 3, 3],
       [2, 2, 3, 2],
       [2, 1, 3, 2]])

In [ ]:
arr2

array([[3, 2, 3, 1],
       [3, 2, 3, 3],
       [1, 3, 1, 3]])

In [ ]:
#Element wise addition
arr1+arr2

array([[5, 4, 6, 4],
       [5, 4, 6, 5],
       [3, 4, 4, 5]])

In [ ]:
#Element wise subtractions
arr1-arr2

array([[-1,  0,  0,  2],
       [-1,  0,  0, -1],
       [ 1, -2,  2, -1]])

In [ ]:
#Element wise multiplication
arr1*arr2

array([[6, 4, 9, 3],
       [6, 4, 9, 6],
       [2, 3, 3, 6]])

In [ ]:
#Element wise division
arr1/arr2

array([[0.66666667, 1.        , 1.        , 3.        ],
       [0.66666667, 1.        , 1.        , 0.66666667],
       [2.        , 0.33333333, 3.        , 0.66666667]])

#### Q8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.




In [ ]:
id_mat=np.eye(5,dtype=int)

In [ ]:
id_mat

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#using slicing
id_mat[[0,1,2,3,4],[0,1,2,3,4]]

array([1, 1, 1, 1, 1])

In [ ]:
#using diagonal
np.diagonal(id_mat)

array([1, 1, 1, 1, 1])

#### Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [ ]:
ar_q9=np.random.randint(0,1001,100)

In [ ]:
ar_q9

array([947, 572, 212, 770, 334, 598, 851, 702, 831, 548, 419, 209, 754,
       939, 925,   9, 746, 492, 211, 744, 727, 935, 286,  10, 782, 972,
       815, 339, 829,  38, 259, 349, 953, 479, 439, 935, 239, 446, 800,
       712, 427, 625, 668, 908, 527, 851, 768, 912, 396, 589, 304, 565,
       109,  41, 494, 238, 357, 906, 349, 166, 378, 405, 175, 777, 481,
       111,  79, 674, 553, 992, 747, 527, 491, 385, 512, 360, 482,   5,
       196, 478,  36,   6,  91, 366, 898,  22, 721, 464, 593, 111, 230,
       560, 925, 160, 858, 653, 789, 919, 617,  66])

In [ ]:
def find_prime(arr):
    prime=[]
    for i in arr:
        if i==1:
            continue
        if i==2:
            prime.append(i)
            continue
        is_prime=True
        for j in range(2,int(i/2)+1):
            if i%j==0:
                is_prime=False
                break
        if is_prime:
            prime.append(i)

    return prime

In [ ]:
l=find_prime(ar_q9)
prime_arr=np.array(l)
prime_arr

array([947, 419, 211, 727, 829, 349, 953, 479, 439, 239, 109,  41, 349,
        79, 491,   5, 593, 653, 919, 617])

#### Q10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
#suppose the temperature is between 20-35 degree celcius
temp=np.random.uniform(20,35,30)

In [ ]:
temperature=np.round(temp,2)

In [ ]:
temperature

array([29.08, 29.25, 20.8 , 23.93, 34.06, 26.05, 29.08, 26.31, 25.25,
       23.18, 21.79, 30.9 , 20.5 , 24.16, 33.63, 29.92, 30.91, 30.63,
       32.32, 29.66, 24.45, 33.26, 25.16, 29.23, 34.09, 31.01, 28.69,
       24.42, 23.25, 30.49])

In [ ]:
temp_week1=temperature[0:7]
print(temp_week1)

# avearge temp of week 1
week_1_avg=np.mean(temp_week1)

print("The average temp of week 1 is :", round(week_1_avg,2))

[29.08 29.25 20.8  23.93 34.06 26.05 29.08]
The average temp of week 1 is : 27.46


In [ ]:
temp_week2=temperature[7:14]
print(temp_week2)

#average temperature of week 2
week_2_avg=np.mean(temp_week2)

print("The average temp of week 1 is :", round(week_2_avg,2))

[26.31 25.25 23.18 21.79 30.9  20.5  24.16]
The average temp of week 1 is : 24.58


In [ ]:
temp_week3=temperature[14:21]
print(temp_week3)

#average temperature of week 3
week_3_avg=np.mean(temp_week3)

print("The average temp of week 1 is :", round(week_3_avg,2))

[33.63 29.92 30.91 30.63 32.32 29.66 24.45]
The average temp of week 1 is : 30.22


In [ ]:
temp_week4=temperature[21:31]
print(temp_week4)

#average temperature of week 4
week_4_avg=np.mean(temp_week4)

print("The average temp of week 1 is :", round(week_4_avg,2))

[33.26 25.16 29.23 34.09 31.01 28.69 24.42 23.25 30.49]
The average temp of week 1 is : 28.84
